version: "3.7"
name: demo
services:
  demo-db:
    hostname: demo-db
    image: postgres:alpine3.18
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456a@"
      POSTGRES_DB: "demo"
    # healthcheck:
    #   test: [ "CMD-SHELL", "pg_isready -U postgres" ]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 10ttp://localhost:8080/api/v1/login/oauth2/code/google
    networks:
      - default

#   demo-app:
#     hostname: demo-app
#     image: kjnwjn/demo:1.0.0
#     ports:
#       - "8300:8080"
#     networks:
#       - default
# networks:
#   default:
#     name: demo-default
